version: '3.8'

services:
  vault_n8n:
    build: .
    env_file:
      - ./.env
    ports:
      - "8200:8000"
    volumes:
      - ./secrets.db:/app/secrets.db # Для сохранения данных SQLite
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
